name: Semantic release

on:
  push:
    branches:
      - main

jobs:
  semantic-release:
    uses: GEWIS/actions/.github/workflows/semantic-release.yml@1.0.0
    with:
      projects: "['.']"
      docker_registry: "abc.docker-registry.gewis.nl"
      docker_paths: "['eou/plankapi']"
      github-registry: "true"
    secrets:
      REGISTRY_USERNAME: ${{ secrets.SVC_GH_ABCEOU_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.SVC_GH_ABCEOU_PWD }}