name: Semantic Release

on:
  workflow_call:
    inputs:
      projects:
        required: true
        description: 'Comma-separated list of projects to release'
        type: string
      version:
        required: true
        description: 'Version of the Docker release'
        type: string
      docker_registry:
        required: true
        type: string
      github_registry:
        required: false
        type: string
      env_file:
        required: false
        description: 'Contents of the ENV file to use during building, should only be used as an exception.'
        type: string
      docker_paths:
        required: true
        description: 'Comma-separated list of Docker paths corresponding to each project'
        type: string
    secrets:
      REGISTRY_USERNAME:
        required: true
      REGISTRY_PASSWORD:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ inputs.version != '' }}
    permissions:
      packages: write
    container:
      image: docker:dind
    strategy:
      matrix:
        project: ${{ fromJson(inputs.projects) }}
        docker_path: ${{ fromJson(inputs.docker_paths) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment
        if: ${{ inputs.env_file != '' }}
        env:
          ENV_FILE: ${{ inputs.env_file }}
        run: |
          echo '${ENV_FILE}' > ${{ matrix.project }}/.env

      - name: Extract Image Name
        id: extract
        run: |
          input="${{ matrix.docker_path }}"
          result="${input#*/}"
          echo "::set-output name=part::$result"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container (GitHub)
        if: ${{ inputs.github_registry == 'true' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image (GitHub)
        if: ${{ inputs.github_registry == 'true' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/gewis/${{ steps.extract.outputs.part }}:latest
            ghcr.io/gewis/${{ steps.extract.outputs.part }}:${{inputs.version}}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: ${{ matrix.project }}/Dockerfile

      - name: Login to Container (Registry)
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.docker_registry }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push Docker Image (Registry)
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ${{ inputs.docker_registry }}/${{ matrix.docker_path }}:latest
            ${{ inputs.docker_registry }}/${{ matrix.docker_path }}:${{ inputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: ${{ matrix.project }}/Dockerfile
