# reusable workflow
name: Docker Build

on:
  workflow_call:
    inputs:
      projects:
        required: true
        description: 'Comma-separated list of projects to build'
        type: string
      docker-registry:
        required: false
        description: 'Docker registry for base images behind authentication'
        type: string
    secrets:
      REGISTRY_USERNAME:
        required: false
      REGISTRY_PASSWORD:
        required: false

jobs:
  dockerize:
    runs-on: ubuntu-latest
    container:
      image: docker:dind
    strategy:
      matrix:
        project: ${{ fromJson(inputs.projects) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          persist-credentials: false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435

      - name: Login to Registry (Custom)
        if: ${{ inputs.docker-registry != '' }}
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1
        with:
          registry: ${{ inputs.docker-registry }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build Docker image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          context: ${{ matrix.project }}
          platforms: linux/amd64
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
