# reusable workflow
name: Docker Build

on:
  workflow_call:
    inputs:
      projects:
        required: true
        description: 'Comma-separated list of projects to build'
        type: string
      docker-registry:
        required: false
        description: 'Docker registry for base images behind authentication'
        type: string
    secrets:
      REGISTRY_USERNAME:
        required: false
      REGISTRY_PASSWORD:
        required: false

jobs:
  dockerize:
    runs-on: ubuntu-latest
    container:
      image: docker:dind
    strategy:
      matrix:
        project: ${{ fromJson(inputs.projects) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd

      - name: Login to Registry (Custom)
        if: ${{ inputs.docker-registry != '' }}
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2
        with:
          registry: ${{ inputs.docker-registry }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build Docker image
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294
        with:
          context: ${{ matrix.project }}
          platforms: linux/amd64
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
