# reusable workflow
name: TypeScript Lint and Build with NPM

on:
  workflow_call:
    inputs:
      working-directory:
        required: false
        type: string
        default: '.'
      node-version:
        required: false
        type: string
        default: '20.x'
      artifact-name:
        required: false
        type: string
        description: 'Name of artifact to use'
      artifact-path:
        required: false
        type: string
        description: 'Path to place artifact'
      prepare-command:
        required: false
        type: string
        description: 'Command to run directly after checkout.'
      cleanup-command:
        required: false
        type: string
        description: 'Command to run after the workflow (even if failed).'
      lint:
        type: boolean
        description: 'Run the lint step.'
        default: true
      format:
        type: boolean
        description: 'Run the format step.'
        default: false
      test:
        type: boolean
        description: 'Run the test step.'
        default: false
      build:
        type: boolean
        description: 'Run the build step.'
        default: true

jobs:
  npm-steps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false

      - name: Artifact
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-path }}
        if: ${{ inputs.artifact-name != '' }}

      - name: Prepare
        env:
          PREPARE_CMD: ${{ inputs.prepare-command }}
        if: ${{ inputs.prepare-command != '' }}
        run: bash -c "$PREPARE_CMD"

      - name: Set Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: ${{ inputs.node-version }}

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        working-directory: ${{ inputs.working-directory }}
        run: npm install

      - name: Lint the project
        working-directory: ${{ inputs.working-directory }}
        run: npm run lint
        if: ${{ inputs.lint }}

      - name: Format the project
        working-directory: ${{ inputs.working-directory }}
        run: npm run format
        if: ${{ inputs.format }}

      - name: Test the project
        working-directory: ${{ inputs.working-directory }}
        run: npm run test
        if: ${{ inputs.test }}

      - name: Build the project
        working-directory: ${{ inputs.working-directory }}
        run: npm run build
        if: ${{ inputs.build }}

      - name: Cleanup
        env:
          CLEANUP_CMD: ${{ inputs.cleanup-command }}
        run: bash -c "$CLEANUP_CMD"
        if: ${{ inputs.cleanup-command != '' && always() }}
