# reusable workflow
name: TypeScript Lint and Build with pnpm

on:
  workflow_call:
    inputs:
      working-directory:
        required: false
        type: string
        default: '.'
      node-version:
        required: false
        type: string
        default: '20.x'
      artifact-name:
        required: false
        type: string
        description: 'Name of artifact to use'
      artifact-path:
        required: false
        type: string
        description: 'Path to place artifact'
      prepare-command:
        required: false
        type: string
        description: 'Command to run directly after checkout.'
      cleanup-command:
        required: false
        type: string
        description: 'Command to run after the workflow (even if failed).'
      lint:
        type: boolean
        description: 'Run the lint step.'
        default: true
      format:
        type: boolean
        description: 'Run the format step.'
        default: false
      test:
        type: boolean
        description: 'Run the test step.'
        default: false
      build:
        type: boolean
        description: 'Run the build step.'
        default: true

jobs:
  pnpm-steps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false

      - name: Artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-path }}
        if: ${{ inputs.artifact-name != '' }}

      - name: Prepare
        env:
          PREPARE_CMD: ${{ inputs.prepare-command }}
        if: ${{ inputs.prepare-command != '' }}
        run: bash -c "$PREPARE_CMD"

      - name: Enable Corepack
        run: corepack enable

      - name: Set up pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271

      - name: Set Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'pnpm'
          cache-dependency-path: ${{ inputs.working-directory }}/pnpm-lock.yaml

      - name: Install dependencies
        working-directory: ${{ inputs.working-directory }}
        run: pnpm install --frozen-lockfile

      - name: Lint the project
        working-directory: ${{ inputs.working-directory }}
        run: pnpm run lint
        if: ${{ inputs.lint }}

      - name: Format the project
        working-directory: ${{ inputs.working-directory }}
        run: pnpm run format
        if: ${{ inputs.format }}

      - name: Test the project
        working-directory: ${{ inputs.working-directory }}
        run: pnpm run test
        if: ${{ inputs.test }}

      - name: Build the project
        working-directory: ${{ inputs.working-directory }}
        run: pnpm run build
        if: ${{ inputs.build }}

      - name: Cleanup
        env:
          CLEANUP_CMD: ${{ inputs.cleanup-command }}
        run: bash -c "$CLEANUP_CMD"
        if: ${{ inputs.cleanup-command != '' && always() }}
