name: TypeScript Lint and Build with Yarn

on:
  workflow_call:
    inputs:
      working-directory:
        required: false
        type: string
        default: '.'
      node-version:
        required: false
        type: string
        default: '20.x'
      artifact-name:
        required: false
        type: string
        description: 'Name of artifact to use'
      artifact-path:
        required: false
        type: string
        description: 'Path to place artifact'
      prepare-command:
        required: false
        type: string
        description: 'Command to run directly after checkout.'
      cleanup-command:
        required: false
        type: string
        description: 'Command to run after the workflow (even if failed).'
      lint:
        type: boolean
        description: 'Run the lint step.'
        default: true
      format:
        type: boolean
        description: 'Run the format step.'
        default: false
      test:
        type: boolean
        description: 'Run the test step.'
        default: false
      build:
        type: boolean
        description: 'Run the build step.'
        default: true

jobs:
  yarn-steps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-path }}
        if: ${{ inputs.artifact-name != '' }}

      - name: Prepare
        run: ${{ inputs.prepare-command }}
        if: ${{ inputs.prepare-command != '' }}

      - name: Set Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install
          dir: ${{ inputs.working-directory }}

      - name: Lint the project
        uses: borales/actions-yarn@v4
        with:
          cmd: lint
          dir: ${{ inputs.working-directory }}
        if: ${{ inputs.lint }}

      - name: Format the project
        uses: borales/actions-yarn@v4
        with:
          cmd: format
          dir: ${{ inputs.working-directory }}
        if: ${{ inputs.format }}

      - name: Test the project
        uses: borales/actions-yarn@v4
        with:
          cmd: test
          dir: ${{ inputs.working-directory }}
        if: ${{ inputs.test }}

      - name: Build the project
        uses: borales/actions-yarn@v4
        with:
          cmd: build
          dir: ${{ inputs.working-directory }}
        if: ${{ inputs.build }}

      - name: Cleanup
        run: ${{ inputs.cleanup-command }}
        if: ${{ inputs.cleanup-command != '' && always() }}
