# reusable workflow
name: TypeScript Lint and Build with Yarn

on:
  workflow_call:
    inputs:
      working-directory:
        required: false
        type: string
        default: '.'
      node-version:
        required: false
        type: string
        default: '20.x'
      artifact-name:
        required: false
        type: string
        description: 'Name of artifact to use'
      artifact-path:
        required: false
        type: string
        description: 'Path to place artifact'
      prepare-command:
        required: false
        type: string
        description: 'Command to run directly after checkout.'
      cleanup-command:
        required: false
        type: string
        description: 'Command to run after the workflow (even if failed).'
      lint:
        type: boolean
        description: 'Run the lint step.'
        default: true
      format:
        type: boolean
        description: 'Run the format step.'
        default: false
      test:
        type: boolean
        description: 'Run the test step.'
        default: false
      build:
        type: boolean
        description: 'Run the build step.'
        default: true

jobs:
  yarn-steps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          persist-credentials: false

      - name: Artifact
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-path }}
        if: ${{ inputs.artifact-name != '' }}

      - name: Prepare
        env:
          PREPARE_CMD: ${{ inputs.prepare-command }}
        if: ${{ inputs.prepare-command != '' }}
        run: bash -c "$PREPARE_CMD"

      - name: Set Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903
        with:
          node-version: ${{ inputs.node-version }}

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        uses: borales/actions-yarn@3766bb1335b98fb13c60eaf358fe20811b730a88
        with:
          cmd: install
          dir: ${{ inputs.working-directory }}

      - name: Lint the project
        uses: borales/actions-yarn@3766bb1335b98fb13c60eaf358fe20811b730a88
        with:
          cmd: lint
          dir: ${{ inputs.working-directory }}
        if: ${{ inputs.lint }}

      - name: Format the project
        uses: borales/actions-yarn@3766bb1335b98fb13c60eaf358fe20811b730a88
        with:
          cmd: format
          dir: ${{ inputs.working-directory }}
        if: ${{ inputs.format }}

      - name: Test the project
        uses: borales/actions-yarn@3766bb1335b98fb13c60eaf358fe20811b730a88
        with:
          cmd: test
          dir: ${{ inputs.working-directory }}
        if: ${{ inputs.test }}

      - name: Build the project
        uses: borales/actions-yarn@3766bb1335b98fb13c60eaf358fe20811b730a88
        with:
          cmd: build
          dir: ${{ inputs.working-directory }}
        if: ${{ inputs.build }}

      - name: Cleanup
        env:
          CLEANUP_CMD: ${{ inputs.cleanup-command }}
        run: bash -c "$CLEANUP_CMD"
        if: ${{ inputs.cleanup-command != '' && always() }}
