# reusable workflow
name: NPM Release

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        description: 'The node version required for the project'
        default: '20.x'
      version:
        required: true
        description: 'Version of the package(s)'
        type: string
      lerna:
        required: false
        description: 'Whether project is a lerna project'
        type: string
      working-directory:
        required: false
        type: string
        description: 'Subdirectory to run npm publish from'
        default: '.'
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    if: ${{ inputs.lerna != 'true' && inputs.version != '' }}
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238
        with:
          node-version: ${{ inputs.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ${{ inputs.working-directory }}/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish
        working-directory: ${{ inputs.working-directory }}
        run: npm version from-git --no-commit-hooks --no-git-tag-version && npm publish --provenance --access public

  publish-npm-lerna:
    runs-on: ubuntu-latest
    if: ${{ inputs.lerna == 'true' && inputs.version != '' }}
    permissions:
      packages: write
      contents: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Git Config
        run: git config user.email 'github-actions@github.com' && git config user.name 'github-actions'

      - name: Setup Node
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238
        with:
          node-version: ${{ inputs.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: echo "provenance=true" >> .npmrc

      - name: Lerna Publish
        env:
          VERSION: ${{ inputs.version }}
        run: |
          npx --yes lerna version "$VERSION" --amend --yes
          npx lerna publish from-git --yes

      - name: Push Tags
        run: git push --force-with-lease --follow-tags
