name: Versioning of the actions repository

on:
  push:
    branches:
      - develop

jobs:
  versioning:
    uses: ./.github/workflows/versioning.yml
    permissions:
      contents: write
      pull-requests: write
      issues: write