name: "Build and Lint TypeScript Project"
description: "Reusable action to build and lint a TypeScript project."

on:
  workflow_call:
    inputs:
      working-directory:
        description: "The directory where the TypeScript project is located."
        type: string
        required: false
        default: "."
      node-version:
        type: choice
        description: "The node version required for the TypeScript project."
        options:
          - 20.x
          - 18.x
          - 22.x
      package-manager:
        description: "The package manager to use for the TypeScript project."
        type: choice
        options:
          - yarn
          - npm
      step-lint:
        type: boolean
        description: "Use the lint step."
      step-format:
        type: boolean
        description: "Use the format step."
      step-test:
        type: boolean
        description: "Use the test step."
      step-build:
        type: boolean
        description: "Use the build step."

jobs:
  build-and-lint-yarn:
    if: ${{ inputs.package-manager }} == 'yarn'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.package-manager }}

      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install
          dir: ${{ inputs.working-directory }}

      - name: Lint the project
        uses: borales/actions-yarn@v4
        with:
          cmd: lint
          dir: ${{ inputs.working-directory }}
        if: ${{ inputs.step-lint }}

      - name: Format the project
        uses: borales/actions-yarn@v4
        with:
          cmd: format
          dir: ${{ inputs.working-directory }}
        if: ${{ inputs.step-format }}

      - name: Test the project
        uses: borales/actions-yarn@v4
        with:
          cmd: test
          dir: ${{ inputs.working-directory }}
        if: ${{ inputs.step-test }}

      - name: Build the project
        uses: borales/actions-yarn@v4
        with:
          cmd: build
          dir: ${{ inputs.working-directory }}
        if: ${{ inputs.step-build }}

  build-and-lint-npm:
    if: ${{ inputs.package-manager }} == 'npm'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.package-manager }}

      - name: Install dependencies
        working-directory: ${{ inputs.working-directory }}
        run: npm install

      - name: Lint the project
        working-directory: ${{ inputs.working-directory }}
        run: npm run lint
        if: ${{ inputs.step-lint }}

      - name: Format the project
        working-directory: ${{ inputs.working-directory }}
        run: npm run format
        if: ${{ inputs.step-format }}

      - name: Test the project
        working-directory: ${{ inputs.working-directory }}
        run: npm run test
        if: ${{ inputs.step-test }}

      - name: Build the project
        working-directory: ${{ inputs.working-directory }}
        run: npm run build
        if: ${{ inputs.step-build }}
