name: 'Validate Workflow Files'

on:
  push:
    paths:
      - '.github/workflows/*.yml'

jobs:
  validate-workflows:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false

      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417
        with:
          go-version: '^1.23.0'

      - run: go install github.com/rhysd/actionlint/cmd/actionlint@latest

      - run: actionlint

  security-analysis:
      runs-on: ubuntu-latest
      permissions:
        security-events: write
        contents: read
      steps:
        - name: Checkout repository
          uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
          with:
            persist-credentials: false

        - name: Install the latest version of uv
          uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57

        - name: Run zizmor
          run: uvx zizmor --format sarif . > results.sarif
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: Upload SARIF file
          uses: github/codeql-action/upload-sarif@v4
          with:
            sarif_file: results.sarif
            category: zizmor