# reusable workflow
name: Versioning

on:
  workflow_call:
    inputs:
      dry-run:
        required: false
        description: 'Whether to perform versioning without making a release'
        type: string
    outputs:
      next-version:
        description: 'Next version for tagging and releasing'
        value: ${{ jobs.versioning.outputs.next-version }}

jobs:
  versioning:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    outputs:
      next-version: ${{ steps.semantic.outputs.new_release_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Fetch Release Config
        run: if [ -f package.json ] && grep -q '"@gewis/release-config"' package.json; then npm install @gewis/release-config; fi

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@ba330626c4750c19d8299de843f05c7aa5574f62
        id: semantic
        with:
          dry_run: ${{ inputs.dry-run }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
